# Generated by Django 3.2.5 on 2022-03-05 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_investment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.investor'),
        ),
        migrations.AddField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.project'),
        ),
    ]
