# Generated by Django 3.2.5 on 2022-03-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220305_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Matured', 'Matured')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='descripton',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
